// File generated by FlutterFire CLI - manually adapted for Web
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android is not yet configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not yet configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not yet configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not yet configured. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not yet configured. Run `flutterfire configure` to generate options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK62z6Qq67PCuepa7EX7soQpHLXbkUnmI',
    appId: '1:659700409826:web:2364a4da7584a813f385bb',
    messagingSenderId: '659700409826',
    projectId: 'sarafun-f9616',
    authDomain: 'sarafun-f9616.firebaseapp.com',
    storageBucket: 'sarafun-f9616.firebasestorage.app',
    measurementId: 'G-MNR0K7FJKR',
  );
}
